---
name: Typos

on: 
  push:
    branches:
      - main
      - dev
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # https://woodruffw.github.io/zizmor/audits/#artipacked
          persist-credentials: false

      - name: typos-action
        uses: crate-ci/typos@v1.28.1
